In [8]:
import pandas as pd

In [86]:
df= pd.read_csv('stat_posts.csv')

In [87]:
df.head()

                                                text
0  <span><span id="ember183" class="ember-view"><...
1  <span><span id="ember266" class="ember-view"><...
2  <span><span id="ember341" class="ember-view"><...
3  <span><span id="ember415" class="ember-view"><...
4  <span><span id="ember489" class="ember-view"><...

In [88]:
from bs4 import BeautifulSoup
soup = BeautifulSoup(df.text[112], 'html.parser')

print(soup.prettify())

<span>
 <span class="ember-view" id="ember9270">
  <span>
   #1: Measure of Central Tendency
      -------------------------------
  A measure of central tendency is a summary statistic that represents the center point or typical value of a dataset. These measures indicate where most values in a distribution fall and are also referred to as the central location of a distribution. It can bethought as the tendency of data to cluster around a middle value.

The following are the various measures of central tendency:
1. Arithmetic Mean
2. Weighted Mean
3. Median
4. Mode
5. Geometric Mean
6. Harmonic Mean
  </span>
  <a class="hashtag-link ember-view" data-control-name="hashtag" href="/feed/hashtag/?highlightedUpdateUrns=urn%3Ali%3Aactivity%3A6559307206632796160&amp;keywords=%23statistics&amp;originTrackingId=l9v96OSRm9NDUGTxl9X8jg%3D%3D" id="ember9273" target="_self">
   <span class="hashtag-a11y ember-view" dir="ltr" id="ember9274">
    <span class="visually-hidden">
     hashtag
    </span>
    <span aria-hidden="true">
     #
    </span>
    <span class="hashtag-a11y__name">
     statistics
    </span>
   </span>
  </a>
  <span>
  </span>
  <a class="hashtag-link ember-view" data-control-name="hashtag" href="/feed/hashtag/?highlightedUpdateUrns=urn%3Ali%3Aactivity%3A6559307206632796160&amp;keywords=%23statisticsfordatascience&amp;originTrackingId=l9v96OSRm9NDUGTxl9X8jg%3D%3D" id="ember9277" target="_self">
   <span class="hashtag-a11y ember-view" dir="ltr" id="ember9278">
    <span class="visually-hidden">
     hashtag
    </span>
    <span aria-hidden="true">
     #
    </span>
    <span class="hashtag-a11y__name">
     statisticsfordatascience
    </span>
   </span>
  </a>
 </span>
</span>
<!-- -->

In [89]:
import re
def striphtml(data):
    p = re.compile(r'<.*?>')
    return p.sub('', data)

In [90]:
df.text= df.text.apply(striphtml)

In [91]:
df.text= df.text.str.strip()

In [92]:
df= df.iloc[:113]

In [93]:
df.to_csv('text_cleaned.csv', index= False)

In [51]:
pd.set_option('display.max_rows', 200)

In [94]:
df= pd.read_csv('text_cleaned.csv')

In [95]:
df

                                                 text
0   #100: Rules Governing Probability Distribution...
1   #99: Analysis of Covariance (ANCOVA)\n----\nAN...
2   #98: Analysis of variance (ANOVA)\n--\nANOVA i...
3   #97: Student's t-test\n---------------------\n...
4   #96: Z-test\n------------\nA z-test is a stati...
5   #95: Key Differences Between Parametric and No...
6   #94: Parametric and Non-parametric Tests\n----...
7   Illustrating Central Limit Theorem\n----------...
8   #93:Parametric Data and Non-parametric Data\n-...
9   #92: Sample Size based on Confidence Interval\...
10  #91: Factors Affecting Confidence Intervals\n-...
11  #90: Relations between Probability Distributio...
12  #89:Geometric Distribution\n----------\nGeomet...
13  #88: Exponential Distribution\n---------------...
14  #87:Poisson Distribution\n--------\nPoisson Di...
15  #86:Poisson Process\n-------\nPoisson Process ...
16  #85:Markov Process\n-----------\nMarkov Proces...
17  #84: Stochastic Process\n---------------------...
18  #83: Memorylessness\n------\nThe memorylessnes...
19  #82:Normal Distribution\n—\n Any distribution ...
20  #81:Binomial Distribution\n——\nA distribution ...
21  #80:Uniform Distribution (Continuous)\n——\nThe...
22  #79: Bernoulli Distribution\n-------------\nTh...
23  #78: Confidence Interval and Confidence Level\...
24  #77: Different Types of Distributions\n----\nT...
25  #76:Population Proportion and Sample Proportio...
26  #75: p-value and its interpretation\n--------\...
27  #74: Level of Statistical Significance\n------...
28  #73: Critical Region or Rejection Region in Hy...
29  #72: Correlation Coefficient\n----------------...
30  #71:Covariance\n------------\nCovariance is a ...
31  #70: Terms in Hypothesis Testing\n-----\nNull ...
32  #69:Hypothesis Testing\n--------\nHypothesis t...
33  #68:Statistical Hypothesis\n------------------...
34  #67: Misunderstanding about Linear and Non-lin...
35  #66:Polynomial Regression\n-------------------...
36  #65:Multiple Linear Regression\n--------------...
37  #64: Non-Linear Regression\n------------------...
38  #63: Regression Coefficient\n-----------------...
39  #62: Linear Regression\n-----------------\nLin...
40  #61:Regression Analysis\n----\nRegression Anal...
41  #60: Correlation Analysis\n-------------------...
42  #59: Principle of Least Square \n-------------...
43  #58: Residual and Error of the Estimate\n-----...
44  #57: Symmetry in Statistics\n-----------------...
45  #56: Standard Deviation and Standard Error\n--...
46  #55: Application of Central Limit Theorem (CLT...
47  #54: Standard Error\n--------------\nThe stand...
48  #53:Z-score\n-----------\nA Z-score is a numer...
49  #52: The Law of Large Numbers (LLN)\n---------...
50  #51: Central Limit Theorem\n------------------...
51  #50: Sampling with replacement and without rep...
52  #49: Probability Mass Function(PMF) &amp; Prob...
53  #48: Probability Distribution Function \n-----...
54  #47: Probability Distribution\n---------------...
55  #46: Cumulative distribution functions (c.d.f....
56  #45: Frequency Distribution\n-----------------...
57  #44: Random Variable\n--------------------\nWh...
58  #43:Independent and identically distributed (I...
59  #42: Asymptotic Theory\n----------------------...
60  #41: Sampling Distribution of Sample Mean\n---...
61  #40: Different Types of Population\n----------...
62  #38: Statistics and Statistic\n---------------...
63  #37: Census vs Sampling on Population\n-------...
64  #36: Types of Data\n----------------------\nN....
65  #35: Scale of Measurement\n-------------------...
66  #34: Measure of Kurtosis\n--------------------...
67  #33: Concept of Kurtosis\n--------------------...
68  #32: Some  facts about Skewness\n-------------...
69  #31: Relative Measures of Skewness\n----------...
70  #30: Absolute Measures of Skewness\n----------...
71  #29: Why skweness occurs? How to overcome skew...
72  #28: Difference between Variance and Skewness\...
73  #27: Skewness\n---------------\nLack of symmet...
74  #26: Moments\n--------------\nMoments are a se...
75  #25: Measure of Central Tendency and Measure o...
76  #24: Coefficient of Variation\n---------------...
77  #23: Root Mean Square Deviation\n-------------...
78  #22: Standard Deviation\n---------------------...
79  #21: Variance of Combined Series\n------------...
80  #20: Variance\n-------------\nVariance is the ...
81  #19: Mean Deviation\n----------------------\nM...
82  #18: Quartile Deviation\n---------------------...
83  #17: Coefficient of Range\n-------------------...
84  #16: Range\n------------\nRange is the simples...
85  #15: Significance of Measures of Dispersion\n-...
86  #14: Measure of Dispersion/Variation\n--------...
87  #13: Partition Values, Quartiles, Deciles ans ...
88  #12: Relation between Arithmetic Mean, Geometr...
89  #11: Geometric Mean\n--------------------\nGeo...
90  #10: Geometric Mean Special\n-----------------...
91  #9:Relationship between Mean, Median and Mode\...
92  #8: Mode\n---------\nHighest frequent observat...
93  #7:Median\n----------\nMedian is that value of...
94  #6: Merits and Demerits of Arithmetic Mean\n--...
95  #5:Properties of Arithmetic Mean\n------------...
96  #4:Properties of a Good Average\n-------------...
97  #3: Significance of the Measure of Central Ten...
98  #2: Some Symbols used in Statistics\nhashtag#s...
99  #1: Measure of Central Tendency\n      -------...

In [48]:
with open('stats_post.txt', 'a+') as f:
    f.write(df.text[112]+ '\n')

In [100]:
for i in range(99,-1,-1):
    with open('stats_post.txt', 'a+', encoding= 'utf-8') as f:
        f.write(df.text[i]+ '\n\n\n\n')

In [101]:
df

                                                 text
0   #100: Rules Governing Probability Distribution...
1   #99: Analysis of Covariance (ANCOVA)\n----\nAN...
2   #98: Analysis of variance (ANOVA)\n--\nANOVA i...
3   #97: Student's t-test\n---------------------\n...
4   #96: Z-test\n------------\nA z-test is a stati...
5   #95: Key Differences Between Parametric and No...
6   #94: Parametric and Non-parametric Tests\n----...
7   Illustrating Central Limit Theorem\n----------...
8   #93:Parametric Data and Non-parametric Data\n-...
9   #92: Sample Size based on Confidence Interval\...
10  #91: Factors Affecting Confidence Intervals\n-...
11  #90: Relations between Probability Distributio...
12  #89:Geometric Distribution\n----------\nGeomet...
13  #88: Exponential Distribution\n---------------...
14  #87:Poisson Distribution\n--------\nPoisson Di...
15  #86:Poisson Process\n-------\nPoisson Process ...
16  #85:Markov Process\n-----------\nMarkov Proces...
17  #84: Stochastic Process\n---------------------...
18  #83: Memorylessness\n------\nThe memorylessnes...
19  #82:Normal Distribution\n—\n Any distribution ...
20  #81:Binomial Distribution\n——\nA distribution ...
21  #80:Uniform Distribution (Continuous)\n——\nThe...
22  #79: Bernoulli Distribution\n-------------\nTh...
23  #78: Confidence Interval and Confidence Level\...
24  #77: Different Types of Distributions\n----\nT...
25  #76:Population Proportion and Sample Proportio...
26  #75: p-value and its interpretation\n--------\...
27  #74: Level of Statistical Significance\n------...
28  #73: Critical Region or Rejection Region in Hy...
29  #72: Correlation Coefficient\n----------------...
30  #71:Covariance\n------------\nCovariance is a ...
31  #70: Terms in Hypothesis Testing\n-----\nNull ...
32  #69:Hypothesis Testing\n--------\nHypothesis t...
33  #68:Statistical Hypothesis\n------------------...
34  #67: Misunderstanding about Linear and Non-lin...
35  #66:Polynomial Regression\n-------------------...
36  #65:Multiple Linear Regression\n--------------...
37  #64: Non-Linear Regression\n------------------...
38  #63: Regression Coefficient\n-----------------...
39  #62: Linear Regression\n-----------------\nLin...
40  #61:Regression Analysis\n----\nRegression Anal...
41  #60: Correlation Analysis\n-------------------...
42  #59: Principle of Least Square \n-------------...
43  #58: Residual and Error of the Estimate\n-----...
44  #57: Symmetry in Statistics\n-----------------...
45  #56: Standard Deviation and Standard Error\n--...
46  #55: Application of Central Limit Theorem (CLT...
47  #54: Standard Error\n--------------\nThe stand...
48  #53:Z-score\n-----------\nA Z-score is a numer...
49  #52: The Law of Large Numbers (LLN)\n---------...
50  #51: Central Limit Theorem\n------------------...
51  #50: Sampling with replacement and without rep...
52  #49: Probability Mass Function(PMF) &amp; Prob...
53  #48: Probability Distribution Function \n-----...
54  #47: Probability Distribution\n---------------...
55  #46: Cumulative distribution functions (c.d.f....
56  #45: Frequency Distribution\n-----------------...
57  #44: Random Variable\n--------------------\nWh...
58  #43:Independent and identically distributed (I...
59  #42: Asymptotic Theory\n----------------------...
60  #41: Sampling Distribution of Sample Mean\n---...
61  #40: Different Types of Population\n----------...
62  #38: Statistics and Statistic\n---------------...
63  #37: Census vs Sampling on Population\n-------...
64  #36: Types of Data\n----------------------\nN....
65  #35: Scale of Measurement\n-------------------...
66  #34: Measure of Kurtosis\n--------------------...
67  #33: Concept of Kurtosis\n--------------------...
68  #32: Some  facts about Skewness\n-------------...
69  #31: Relative Measures of Skewness\n----------...
70  #30: Absolute Measures of Skewness\n----------...
71  #29: Why skweness occurs? How to overcome skew...
72  #28: Difference between Variance and Skewness\...
73  #27: Skewness\n---------------\nLack of symmet...
74  #26: Moments\n--------------\nMoments are a se...
75  #25: Measure of Central Tendency and Measure o...
76  #24: Coefficient of Variation\n---------------...
77  #23: Root Mean Square Deviation\n-------------...
78  #22: Standard Deviation\n---------------------...
79  #21: Variance of Combined Series\n------------...
80  #20: Variance\n-------------\nVariance is the ...
81  #19: Mean Deviation\n----------------------\nM...
82  #18: Quartile Deviation\n---------------------...
83  #17: Coefficient of Range\n-------------------...
84  #16: Range\n------------\nRange is the simples...
85  #15: Significance of Measures of Dispersion\n-...
86  #14: Measure of Dispersion/Variation\n--------...
87  #13: Partition Values, Quartiles, Deciles ans ...
88  #12: Relation between Arithmetic Mean, Geometr...
89  #11: Geometric Mean\n--------------------\nGeo...
90  #10: Geometric Mean Special\n-----------------...
91  #9:Relationship between Mean, Median and Mode\...
92  #8: Mode\n---------\nHighest frequent observat...
93  #7:Median\n----------\nMedian is that value of...
94  #6: Merits and Demerits of Arithmetic Mean\n--...
95  #5:Properties of Arithmetic Mean\n------------...
96  #4:Properties of a Good Average\n-------------...
97  #3: Significance of the Measure of Central Ten...
98  #2: Some Symbols used in Statistics\nhashtag#s...
99  #1: Measure of Central Tendency\n      -------...

In [102]:
import PyPDF2