In [1]:
import pandas as pd
import re

In [2]:
df= pd.read_csv('top_voices.csv')

In [3]:
df.date= df.date.apply(lambda x: x.split('\n  \n')[:-1])

In [4]:
def clean_date(text):
    text= [re.sub(r'( • )', '', t) for t in text]
    text= [t.strip() for t in text]
    text= [re.sub(r'(Edited)?', '', t) for t in text]
    text= [re.sub(r'(Published)?', '', t) for t in text]
    return text

In [5]:
df.date= df.date.apply(clean_date)

In [6]:
test_list= ['7mo', '8mo', '9mo', '10mo', '11mo', '12mo', '1yr']

In [7]:
def rem_dat(text):
    return [x for x in text if x not in test_list]

In [8]:
df.date= df.date.apply(rem_dat)

In [9]:
import ast

In [10]:
df.likes= df.likes.apply(ast.literal_eval)

In [11]:
df.columns

Index(['names', 'headline', 'links', 'followers', 'date', 'num_posts', 'likes',
       'comments'],
      dtype='object')

In [12]:
df.comments= df.comments.apply(ast.literal_eval)

In [13]:
df.columns

Index(['names', 'headline', 'links', 'followers', 'date', 'num_posts', 'likes',
       'comments'],
      dtype='object')

In [14]:
df.followers= df.followers.apply(lambda x: int(x.replace(',', '')))

In [15]:
df.likes= df.likes.apply(lambda x: [int(t.replace(',', '')) for t in x])

In [16]:
df.comments= df.comments.apply(lambda x: [t.replace(' Comments', '') for t in x])

In [17]:
df.comments= df.comments.apply(lambda x: [t.replace(' Comment', '') for t in x])

In [18]:
df.comments= df.comments.apply(lambda x: [int(t.replace(',', '')) for t in x])

In [19]:
df.head()

,names,headline,links,followers,date,num_posts,likes,comments
0,Ritu Anand,Chief Leadership & Diversity Officer at TCS,https://www.linkedin.com/in/ritu-anand-9343065/,22041,"[1h, 1w, 1w, 2w, 3w, 1mo, 1mo, 1mo, 1mo, 1mo, ...",35,"[160, 1114, 1111, 906, 483, 290, 132, 802, 458...","[6, 116, 54, 65, 40, 20, 10, 58, 17, 87, 18, 1..."
1,Harish Bhat,"Brand Custodian, Tata Sons. Passionate markete...",https://www.linkedin.com/in/harishbhattata/,22040,"[4d, 1w, 2w, 3w, 3w, 1mo, 1mo, 1mo, 1mo, 2mo, ...",30,"[248, 770, 665, 577, 190, 62, 360, 627, 415, 9...","[27, 366, 31, 100, 93, 13, 139, 203, 28, 77, 2..."
2,Rekha M Menon,Chairman and Senior Managing Director - Accent...,https://www.linkedin.com/in/rekha-m-menon-15325/,135476,"[1d, 2d, 3d, 3d, 6d, 1w, 1w, 2w, 2w, 2w, 2w, 3...",65,"[273, 105, 69, 80, 269, 157, 88, 141, 377, 112...","[9, 1, 2, 10, 3, 5, 5, 6, 3, 10, 31, 5, 4, 4, ..."
3,Satyarth Priyedarshi,"Head of Digital, TATA AIA || Ex-Google, Jio, F...",https://www.linkedin.com/in/satyarth/,68365,"[1h, 23h, 1d, 2d, 4d, 5d, 5d, 1w, 1w, 1w, 1w, ...",125,"[142, 111, 712, 84, 145, 325, 191, 78, 5360, 6...","[14, 7, 79, 2, 11, 18, 13, 3, 244, 35, 8, 19, ..."
4,Adhil Shetty,CEO at BankBazaar.com,https://www.linkedin.com/in/adhilshetty/,652793,"[3h, 1d, 4mo, 5mo, 6mo, 6mo, 6mo, 6mo]",10,"[62, 91, 411, 888, 197, 479, 266, 364, 262, 1060]","[1, 5, 9, 16, 7, 14, 14, 7, 4, 12]"

In [20]:
for i in range(df.shape[0]):
    df.likes[i]= df.likes[i][:len(df.date[i])]
    df.comments[i]= df.comments[i][:len(df.date[i])]

C:\Users\Aman\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Aman\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [21]:
df['avg_likes']= ''
df['avg_comments']= ''
import numpy as np
for i in range(df.shape[0]):
    df.avg_likes[i]= np.mean(df.likes[i])
    df.avg_comments[i]= np.mean(df.comments[i])

C:\Users\Aman\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\Users\Aman\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [22]:
df.head()

,names,headline,links,followers,date,num_posts,likes,comments,avg_likes,avg_comments
0,Ritu Anand,Chief Leadership & Diversity Officer at TCS,https://www.linkedin.com/in/ritu-anand-9343065/,22041,"[1h, 1w, 1w, 2w, 3w, 1mo, 1mo, 1mo, 1mo, 1mo, ...",35,"[160, 1114, 1111, 906, 483, 290, 132, 802, 458...","[6, 116, 54, 65, 40, 20, 10, 58, 17, 87, 18, 1...",764.029,44.6471
1,Harish Bhat,"Brand Custodian, Tata Sons. Passionate markete...",https://www.linkedin.com/in/harishbhattata/,22040,"[4d, 1w, 2w, 3w, 3w, 1mo, 1mo, 1mo, 1mo, 2mo, ...",30,"[248, 770, 665, 577, 190, 62, 360, 627, 415, 9...","[27, 366, 31, 100, 93, 13, 139, 203, 28, 77, 2...",901.08,105.04
2,Rekha M Menon,Chairman and Senior Managing Director - Accent...,https://www.linkedin.com/in/rekha-m-menon-15325/,135476,"[1d, 2d, 3d, 3d, 6d, 1w, 1w, 2w, 2w, 2w, 2w, 3...",65,"[273, 105, 69, 80, 269, 157, 88, 141, 377, 112...","[9, 1, 2, 10, 3, 5, 5, 6, 3, 10, 31, 5, 4, 4, ...",225.29,6.98182
3,Satyarth Priyedarshi,"Head of Digital, TATA AIA || Ex-Google, Jio, F...",https://www.linkedin.com/in/satyarth/,68365,"[1h, 23h, 1d, 2d, 4d, 5d, 5d, 1w, 1w, 1w, 1w, ...",125,"[142, 111, 712, 84, 145, 325, 191, 78, 5360, 6...","[14, 7, 79, 2, 11, 18, 13, 3, 244, 35, 8, 19, ...",405.05,28.7966
4,Adhil Shetty,CEO at BankBazaar.com,https://www.linkedin.com/in/adhilshetty/,652793,"[3h, 1d, 4mo, 5mo, 6mo, 6mo, 6mo, 6mo]",10,"[62, 91, 411, 888, 197, 479, 266, 364]","[1, 5, 9, 16, 7, 14, 14, 7]",344.75,9.125

In [23]:
import numpy as np
for i in range(df.shape[0]):
    df.num_posts[i]= len(df.date[i])

C:\Users\Aman\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [93]:
df.to_csv('clean_data.csv', index= False)

In [27]:
df['likes_per_thousand']= ''
for i in range(df.shape[0]):
    df.likes_per_thousand[i]= [like/df.followers[i] * 1000 for like in df.likes[i]]

C:\Users\Aman\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [28]:
df.likes_per_thousand

0     [7.25919876593621, 50.542171407830864, 50.4060...
1     [11.252268602540834, 34.936479128856625, 30.17...
2     [2.015117068705896, 0.7750450264253447, 0.5093...
3     [2.0770862283332114, 1.6236378263731441, 10.41...
4     [0.09497650863290508, 0.13940100460636065, 0.6...
5     [0.21739721188075764, 3.668577950487785, 0.217...
6     [0.36319523581957874, 0.2926147851339926, 0.56...
7     [6.418934911242603, 32.73372781065089, 9.94082...
8     [1.9529032404568885, 38.369250100294444, 6.373...
9     [2.4441566850113303, 14.891550663645193, 33.47...
10    [0.20843859104575, 0.12007875353722555, 0.0453...
11    [18.213512863669152, 58.187064198124546, 5.590...
12    [0.8568935244083229, 2.0344649935338706, 2.581...
13    [2.439173368624657, 2.9237503817571007, 2.6712...
14    [1.9738596959189116, 44.81194985329421, 2.7207...
15    [4.08099199497724, 3.1392246115209543, 1.44404...
16    [8.854539871020576, 7.626164397584195, 6.03951...
17    [16.034691407825736, 14.219443323920935, 23.79...
18    [2.8968166503983124, 3.9044050505368557, 2.676...
19    [0.34197554386324885, 4.543389368468878, 2.252...
20    [5.563462284901022, 4.010868158882132, 12.2913...
21    [0.29581857505563736, 0.6053505939880263, 0.15...
22    [62.49323080255605, 31.19246182172642, 16.0294...
Name: likes_per_thousand, dtype: object

In [29]:
df['commnets_per_thousand']= ''
for i in range(df.shape[0]):
    df.commnets_per_thousand[i]= [comment/df.followers[i] * 1000 for comment in df.comments[i]]

C:\Users\Aman\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [30]:
df['avg_likes_per_thousand']= ''
df['avg_comments_per_thousand']= ''
import numpy as np
for i in range(df.shape[0]):
    df.avg_likes_per_thousand[i]= np.mean(df.likes_per_thousand[i])
    df.avg_comments_per_thousand[i]= np.mean(df.commnets_per_thousand[i])

C:\Users\Aman\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\Users\Aman\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [32]:
df.to_csv('new_clean_data.csv', index= False)